# Generated by Django 3.2.4 on 2021-06-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210612_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug_uz',
        ),
    ]
