# Generated by Django 3.2.4 on 2021-06-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_uz',
        ),
    ]
